CREATE DATABASE TP1B
GO
USE TP1B
GO

CREATE TABLE CARRERAS
(
		IDCARRERA INT NOT NULL PRIMARY KEY,
		NOMBRE VARCHAR(20) NOT NULL,
)
GO

ALTER TABLE CARRERAS
ALTER COLUMN NOMBRE VARCHAR(100) NOT NULL

UPDATE CARRERAS SET NOMBRE ='INGENIERIA MECANICA' WHERE IDCARRERA=2
DELETE FROM CARRERAS WHERE IDCARRERA=3


CREATE TABLE MATERIAS
(

		IDMATERIA INT NOT NULL PRIMARY KEY,
		NOMBRE VARCHAR(30) NOT NULL,
		IDCARRERA INT NOT NULL FOREIGN KEY REFERENCES CARRERAS(IDCARRERA),

		/*PRIMARY KEY(IDMATERIA,IDCARRERA),*/
)
GO
ALTER TABLE MATERIAS
ALTER COLUMN NOMBRE VARCHAR(100) NOT NULL

INSERT INTO MATERIAS (IDMATERIA, NOMBRE, IDCARRERA) VALUES (1,'LABORATORIO DE COMPUTACION 1',1)
INSERT INTO MATERIAS (IDMATERIA,NOMBRE,IDCARRERA) VALUES(2,'LABORATORIO DE COMPUTACION 2',1)
INSERT INTO MATERIAS (IDMATERIA,NOMBRE,IDCARRERA) VALUES(3,'FUNDAMENTOS DE INFORMATICA',2)

CREATE TABLE ALUMNOS
(

	IDLEGAJO INT NOT NULL PRIMARY KEY,
	Dni int not null UNIQUE,
	nombre varchar(100) not null,
	apellido varchar(100) not null,
	
)
GO

ALTER TABLE ALUMNOS 
ADD IDCARRERA INT NOT NULL FOREIGN KEY REFERENCES CARRERAS(IDCARRERA)



INSERT INTO ALUMNOS (idlegajo,dni,nombre,apellido,IDCARRERA) VALUES (1,38942511,'Jerry','Seinfeld',1)
INSERT INTO ALUMNOS (IDLEGAJO,DNI,NOMBRE,APELLIDO,IDCARRERA) VALUES(2,39876278,'George','Costanza',1)
INSERT INTO ALUMNOS (IDLEGAJO,DNI,NOMBRE,APELLIDO,IDCARRERA) VALUES(3,40323232,'Elaine','Benes',2)


CREATE TABLE EXAMENES
(
	MATERIA INT NOT NULL FOREIGN KEY REFERENCES MATERIAS(IDMATERIA),
	LEGAJO INT NOT NULL FOREIGN KEY REFERENCES ALUMNOS(IDLEGAJO),
	FECHA DATE NOT NULL,
	NOTA TINYINT NOT NULL CHECK(NOTA >=0 OR NOTA <=10),
	PRIMARY KEY(MATERIA,LEGAJO,FECHA),
)
GO


INSERT INTO EXAMENES (MATERIA,LEGAJO,FECHA,NOTA) VALUES(1,1,'2014/05/01',9)
INSERT INTO EXAMENES (MATERIA, LEGAJO,FECHA,NOTA) VALUES(2,1,'2014/05/01',9)
INSERT INTO	EXAMENES (MATERIA, LEGAJO, FECHA, NOTA) VALUES(1,2,'2014/05/11',6)
INSERT INTO EXAMENES (MATERIA, LEGAJO, FECHA, NOTA) VALUES(3,3,'2014/05/02',10)


DELETE FROM MATERIAS WHERE IDMATERIA=4
